// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymdhgxfpmjvclwouzvld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltZGhneGZwbWp2Y2x3b3V6dmxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTM3NjYsImV4cCI6MjA2NjE2OTc2Nn0.831pO2SYLHup8zymH6oP7EXu5pDaEBidWNc8xzA_Hms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);